source 'https://rubygems.org'
ruby '2.3.3'

gem 'capistrano', '~> 3.7'
gem 'capistrano-bundler'
gem 'capistrano-rails', '~> 1.1.0'
gem 'capistrano-rails-console', require: false
gem 'rvm1-capistrano3'
gem 'capistrano3-unicorn'
